name: Data Checking & Update

on:
  push:
    branches:
      - main
      - etl_process
  workflow_dispatch:

jobs:
  data_check_update:
    runs-on: ubuntu-latest

    env:
      AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
      AZURE_SQL_PASS: ${{ secrets.AZURE_SQL_PASS }}
      AZURE_SQL_URL: ${{ secrets.AZURE_SQL_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data checking
        run: |
          python Data_checking.py

      - name: Run update script
        if: success()  # chỉ chạy khi file checking không lỗi
        run: |
          python updated_data.py
