name: Run ETL and Update Data

on:
  push:
    branches:
      - main

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from etl_process
        uses: actions/checkout@v4
        with:
          ref: etl_process

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data checking
        run: python Data_checking.py

      - name: Run update script
        run: python updated_data.py
