name: ETL Checking and Update

on:
  push:
    branches:
      - etl_process
  workflow_dispatch:

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Go to project root
        run: cd $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Checking
        run: |
          cd $GITHUB_WORKSPACE
          python Data_checking.py

      - name: Run Update Script
        run: |
          cd $GITHUB_WORKSPACE
          python updated_data.py
